AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - Rakefile
    - gruf-commander.gemspec

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20
